name: Package
on:
  push:
    branches:
      - master
    paths:
      - 'CleanArcTemplate.nuspec'
jobs:

  publish:
  
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      
      - name: "run xUnit"
        run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
       
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
         name: Unit Tests
         path: "**/test-results.trx"                            
         reporter: dotnet-trx
         fail-on-error: true

      - name: Create the package
        run: nuget pack CleanArcTemplate.nuspec -NoDefaultExcludes
        
      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
